import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/header";

const HagoFont = localFont({
  src: "./fonts/Hago-Regular.woff",
  variable: "--font-hago",
  weight: "100 900",
});

const MatroskaFont = localFont({
  src: "./fonts/Matroska.woff",
  variable: "--font-matroska",
  weight: "100 900",
});

const FuturaFont = localFont({
  src: "./fonts/FuturaLT.woff",
  variable: "--font-futura",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${MatroskaFont.variable} ${HagoFont.variable} ${FuturaFont.variable}antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
